### ISSUE TITLE
ThinkJS 3.x development task

### ISSUE THREAD

**Issue by welefen** [thinkjs/thinkjs#564]
## TODO

* [ ] [think-websocket-sockjs](https://github.com/thinkjs/think-websocket-sockjs)
* [ ] [think-webpack](https://github.com/thinkjs/think-webpack) webpack hot dev sever
* [ ] [think-waterline](https://github.com/thinkjs/think-waterline)  think waterline wrapper
* [ ] [think-passport](https://github.com/thinkjs/think-passport)  think passport wrapper
* [ ] [think-auth](https://github.com/thinkjs/think-auth)  access authentication
* [ ] [think-rpc](https://github.com/thinkjs/think-rpc)  RPC
* [ ] [think-html-staticize](https://github.com/thinkjs/think-html-staticize)  html staticize
* [ ] [think-firebase](https://github.com/thinkjs/think-firebase) 

[开发文档](https://github.com/thinkjs/thinkjs/wiki/3.0-%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3)

## Developing

* [ ] [think-mock](https://github.com/thinkjs/think-mock)  mock data @lushijie
* [ ] [think-pwa](https://github.com/thinkjs/think-pwa)  @toxic-johann
* [ ] [think-csp](https://github.com/thinkjs/think-csp) @huangxiaolu

## Finished
* [x] [think-monitor](https://github.com/thinkjs/think-monitor)  cpu, memory monitor @sijiecai
* [x] [think-cli](https://github.com/thinkjs/think-cli) @songguangyu 
* [x] [think-cors](https://github.com/thinkjs/think-cors) 
* [x] [think-websocket](https://github.com/thinkjs/think-websocket) websocket extend
* [x] [think-websocket-socket.io](https://github.com/thinkjs/think-websocket-socket.io)
* [x] [think-session-mysql](https://github.com/thinkjs/think-session-mysql)  @zhengqingxin
* [x] [think-csrf](https://github.com/thinkjs/think-csrf) CSRF authentication @berwin
* [x] [think-email](https://github.com/thinkjs/think-email) @lushijie
* [x] [think-loader](https://github.com/thinkjs/think-loader) @welefen @SijieCai
* [x] [think-model](https://github.com/thinkjs/think-model)  @lizheming 
* [x] [think-crontab](https://github.com/thinkjs/think-crontab) @welefen 
* [x] [think-cluster](https://github.com/thinkjs/think-cluster) @welefen 
* [x] [think-delegate](https://github.com/thinkjs/think-delegate) @welefen 
* [x] [think-gc](https://github.com/thinkjs/think-gc) @welefen 
* [x] [think-svg-captcha](https://github.com/thinkjs/think-svg-captcha)  captcha library @lushijie
* [x] [think-view-ejs](https://github.com/thinkjs/think-view-ejs)  @huangxiaolu 
* [x] [think-memcache](https://github.com/thinkjs/think-memcache) @lushijie
* [x] [think-cache-memcache](https://github.com/thinkjs/think-cache-memcache) @lushijie
* [x] [think-trace](https://github.com/thinkjs/think-trace) @lizheming 
* [x] [think-redis](https://github.com/thinkjs/think-redis) @lushijie
* [x] [think-cache-redis](https://github.com/thinkjs/think-cache-redis) @lushijie
* [x] [think-cache-file](https://github.com/thinkjs/think-cache-file) @lushijie
* [x] [think-store-file](https://github.com/thinkjs/think-store-file)   @lushijie 
* [x] [think-inspect](https://github.com/thinkjs/think-inspect)   @huangxiaolu 
* [x] [think-logger](https://github.com/thinkjs/think-logger) @lizheming 
* [x] [think-cache](https://github.com/thinkjs/think-cache) @welefen  @lushijie
* [x] [think-view-pug](https://github.com/thinkjs/think-view-pug)  @lushijie 
* [x] [think-view-handlebars](https://github.com/thinkjs/think-view-handlebars)  @lushijie
* [x] [think-view-ejs](https://github.com/thinkjs/think-view-ejs)  @huangxiaolu @welefen
* [x] [think-view](https://github.com/thinkjs/think-view)  @zhengqingxin @welefen
* [x] [think-view-nunjucks](https://github.com/thinkjs/think-view-nunjucks)  @lushijie
* [x] [think-validator](https://github.com/thinkjs/think-validator)  @lushijie
* [x] [think-await](https://github.com/thinkjs/think-await)   @huangxiaolu @welefen
* [x] [think-babel](https://github.com/thinkjs/think-babel)   @lushijie  
* [x] [think-typescript](https://github.com/thinkjs/think-typescript)   @lushijie 
* [x] [think-helper](https://github.com/thinkjs/think-helper)   @songguangyu @welefen
* [x] [think-watcher](https://github.com/thinkjs/think-watcher) @welefen
* [x] [think-session](https://github.com/thinkjs/think-session) @huangxiaolu 
* [x] [think-session-cookie](https://github.com/thinkjs/think-session-cookie)  @zhengqingxin 
* [x] [think-session-file](https://github.com/thinkjs/think-session-file) @huangxiaolu @welefen
* [x] [think-session-redis](https://github.com/thinkjs/think-session-redis) @huangxiaolu
* [x] [think-fetch](https://github.com/thinkjs/think-fetch)  @berwin
* [x] [think-resource](https://github.com/thinkjs/think-resource)  @xiamingxing 
* [x] [think-i18n](https://github.com/thinkjs/think-i18n)  i18n @sijiecai
* [x] [think-mysql](https://github.com/thinkjs/think-mysql)  @zhengqingxin
* [x] [think-payload](https://github.com/thinkjs/think-payload) @berwin
